"""Operator Desk error codes and exceptions."""
from __future__ import annotations


class OperatorError(Exception):
    """Base error with stable machine-readable code."""

    def __init__(self, code: str, message: str) -> None:
        self.code = code
        self.message = message
        super().__init__(f"{code}: {message}")


OPERATOR_CONFIG_INVALID = "OPERATOR_CONFIG_INVALID"
JOB_NOT_FOUND = "JOB_NOT_FOUND"
EMAIL_ACCOUNT_NOT_FOUND = "EMAIL_ACCOUNT_NOT_FOUND"
EMAIL_AUTH_UNAVAILABLE = "EMAIL_AUTH_UNAVAILABLE"
EMAIL_RATE_LIMITED = "EMAIL_RATE_LIMITED"
GROWFLOW_SNAPSHOT_MISSING = "GROWFLOW_SNAPSHOT_MISSING"
GROWFLOW_SNAPSHOT_STALE = "GROWFLOW_SNAPSHOT_STALE"
GROWFLOW_API_UNAVAILABLE = "GROWFLOW_API_UNAVAILABLE"
GROWFLOW_SCHEMA_MISMATCH = "GROWFLOW_SCHEMA_MISMATCH"
APPROVAL_SERVICE_UNAVAILABLE = "APPROVAL_SERVICE_UNAVAILABLE"
APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
ACTION_NOT_ALLOWLISTED = "ACTION_NOT_ALLOWLISTED"
REPO_REGISTRY_INVALID = "REPO_REGISTRY_INVALID"
DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
OPERATOR_DISABLED = "OPERATOR_DISABLED"
